travis:
  secure:
    BINSTAR_TOKEN: SSdOxLgjnUlmyfvfsz5jVoVVHQjRpR6okbjaZitCxpDM6twSxDoshm3ocrmBKGhaxJCTT4IEqwEWkzhTqmsyZB+q2FmLR2VLSYDBTMLlpztefZHriqdP9UXxL4Xh7KktvilttSNgFupUgZ8z85WPmW1QmcEpnPWdsEtUICcjZq4jnzRzQKIfRARfoo8P3duAddtX0ZyTrX38EkN/zFLvLqBOUJcURqKsSlOxEmYfjoga8t5skBIbtaDHMOnZ4R3oUpg2DJENgNb+lB7ihD3YL4iUcvP77W3OrZqqt1EbwcDJk3dQZ5kZXh7vr4XOfQgVBuMFMEJJCAUmRbtH4Vlru3Bh1d3CdneVCt0d3N4GINPc8oWVd9rN7TnrfgLcZ8AVrg9lHjcpx71q9zWUnAQIAqGGkFiqZAdwNCvXAvnYmH+7pqQy1VP2J6dMIfDucjX4nsAsrGosPpjcYEpQiQUScpHBLofKdlG+be8zp+cJWxlxrDSUvE0t3EyH7bzgNFsLuriMWLCYDebHJRfwJrUVYhmGFecxggXD1zCUL8lfIBMFFZuxDZGR33tSMtvLqcXD5fcsiRrVXqX3Tngyu+BuJbP2TyasDVXKhQIPx6RD0ncM/ubg7Ii7l+tspZcoIUG/hwF4KqIHyS3bhxCJf5lIARQXFLTUGFG2ziddAk9CuqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
